#!/usr/bin/ruby -Ku
# encoding: utf-8

require 'optparse'

TakibiConf = {}
TAKIBI_ROOT = File.join(File.dirname(__FILE__), "..")
opt = OptionParser.new

opt.on("-f feed", "--feed feed",
       "specify a feed for action") do |feed|
  TakibiConf["feed"] = feed
end

opt.on("-a action", "--action action",
       [:crawl_rss, :crawl_article, :epub, :test_article]) do |action|
  TakibiConf["action"] = action
end

opt.on("-o filename", "--output filename",
       "output filename (usually used  --action epub)") do |filename|
  TakibiConf["filename"] = filename
end
opt.on("-c condition", "--condition condition",
       "output articles which matches specified condition") do |cond|
  TakibiConf["condition"] = cond
end
opt.parse!(ARGV)

require File.join(TAKIBI_ROOT, "lib", "takibi")

feed = TakibiConf["feed"]
feed = feed.to_s if feed
plugin_dir = if feed then
               File.join(TAKIBI_ROOT, "plugins", feed.to_s)
             else
               File.join(TAKIBI_ROOT, "plugins", "*")
             end
case TakibiConf["action"]
when :crawl_rss
  Dir.glob(File.join(plugin_dir, "*_crawler.rb")) do |filename|
    require filename
  end
  if feed then
    crawler = Takibi.const_get(feed.capitalize + "Crawler")
    crawler.crawl_rss
  else
    Takibi.constants.grep(/.+Crawler$/) do |classname|
      crawler = Takibi.const_get(classname)
      crawler.crawl_rss
    end
  end
when :crawl_article
  Dir.glob(File.join(plugin_dir, "*_crawler.rb")) do |filename|
    require filename
  end
  if feed then
    crawler = Takibi.const_get(feed.capitalize + "Crawler")
    crawler.crawl_article
  else
    Takibi.constants.grep(/.+Crawler$/) do |classname|
      crawler = Takibi.const_get(classname)
      crawler.crawl_article
    end
  end
when :epub
  options = []
  require File.join(TAKIBI_ROOT, "lib", "formatter.rb")
  case TakibiConf["condition"]
  when "last24hours"
    options << ["published_time > ?", Time.now - 60*60*24]
  when "last3days"
    options << ["published_time > ?", Time.now - 60*60*24*3]
  when "last5days"
    options << ["published_time > ?", Time.now - 60*60*24*5]
  when "last7days"
    options << ["published_time > ?", Time.now - 60*60*24*7]
  end
  if feed then
    options << "feed = '#{feed}'"
  end
  Takibi::Formatter.epub TakibiConf["filename"], options
when :test_article
  require File.join(TAKIBI_ROOT, "lib", "parser.rb")
  url = "http://news.nifty.com/cs/topics/detail/110101351445/1.htm"
  h = Takibi::Crawler.get_whole_article	url
  pp h
end

